# Experiment Configuration
experiment:
  name: "fssm_text_classification"
  seed: 44

# Data Configuration
data:
  data_path: "data/aclImdb/data.pt"
  batch_size: 50
  total_samples: 25000
  test_samples: 25000
  text_len: 4000
  num_workers: 4

# Model Configuration
model:
  hidden_size: 64
  step: 0.001
  activation: 'tanh'
  emb_dim: 64
  embedding_vocab_size: 256
  num_classes: 2

  # FSSM specific parameters
  fssm:
    mid_layers: 2
    skip: true
    dropout: 0.0
    norm: 'BN'
    h: 0.3
    final_act: 'sigmoid'
    feed_act: 'tanh'
    use_flash: False

# Training Configuration
training:
  epochs: 20
  device: "cuda:3"

  # Loss configuration
  loss:
    h_loss_weight: 0.3

  # Optimizer configuration
  optimizer:
    type: 'AdamW'
    weight_decay: 0.05
    ssm_lr: 0.001
    other_lr: 0.01

  # Scheduler configuration
  scheduler:
    type: 'cosine'  # options: 'sequential', 'cosine', 'plateau'
    warmup_epochs: 3
    warmup_start_factor: 0.000001
    cosine_eta_min: 0
    # For plateau scheduler (if used)
    plateau_mode: 'max'
    plateau_factor: 0.5
    plateau_threshold: 0.3
    plateau_patience: 4

# Saving Configuration
saving:
  save_interval: 2  # save every N epochs
  model_dir: "../../model/text"

# Logging Configuration
logging:
  level: "INFO"
  save_history: true